apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-cluster-test
  region: us-east-1
  version: "1.21"

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["all"]
        # enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"